"""Add user_id and terms fields v2

Revision ID: 6ce456f9a623
Revises: 20250101_add_user_id_and_terms
Create Date: 2025-06-01 21:24:29.016228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ce456f9a623'
down_revision: Union[str, None] = '20250101_add_user_id_and_terms'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnosis_results', sa.Column('choice_strategy_analysis', sa.JSON(), nullable=True, comment='선택 전략 분석'))
    op.add_column('diagnosis_results', sa.Column('elimination_effectiveness', sa.Float(), nullable=True, comment='제거 전략 효과성 (0.0-1.0)'))
    op.add_column('diagnosis_results', sa.Column('decision_confidence_score', sa.Float(), nullable=True, comment='의사결정 확신도 점수'))
    op.add_column('diagnosis_results', sa.Column('cognitive_load_analysis', sa.JSON(), nullable=True, comment='인지 부하 분석'))
    op.alter_column('questions', 'is_duplicate',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('users', sa.Column('admission_year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.drop_index(op.f('ix_users_student_id'), table_name='users')
    op.create_index(op.f('ix_users_student_id'), 'users', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_student_id'), table_name='users')
    op.create_index(op.f('ix_users_student_id'), 'users', ['student_id'], unique=True)
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'admission_year')
    op.alter_column('questions', 'is_duplicate',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('diagnosis_results', 'cognitive_load_analysis')
    op.drop_column('diagnosis_results', 'decision_confidence_score')
    op.drop_column('diagnosis_results', 'elimination_effectiveness')
    op.drop_column('diagnosis_results', 'choice_strategy_analysis')
    # ### end Alembic commands ###
